SELECT SUM(re.RENTING) AS RENTING_COUNT, SUM(re.SELLING) AS SELLING_COUNT, re.CITY, 100.0 * SUM(re.RENTING) / SUM(re.SELLING) AS RENTING_TO_SELLING_PERCENT, SUM(re.SELLING) + SUM(re.RENTING) AS TOTAL
FROM
(
    SELECT IF(OFFER_TYPE = 'izdavanje', 1, 0) AS RENTING,
           IF(OFFER_TYPE = 'prodaja', 1, 0) AS SELLING,
           CITY
    FROM real_estate_tbl
) re
GROUP BY re.CITY
ORDER BY TOTAL DESC
LIMIT 8